// test main dpeg generated by make-c-tests-main

// Includes
#include "dpeg_c.h"

int main () {

 printf("dpeg.test_wspace1 ==> %s\n", dpeg__test_wspace1() ? "true" : "false");

 printf("dpeg.test_wspace2 ==> %s\n", dpeg__test_wspace2() ? "true" : "false");

 printf("dpeg.test_wspace3 ==> %s\n", dpeg__test_wspace3() ? "true" : "false");

 printf("dpeg.test_wspace4 ==> %s\n", dpeg__test_wspace4() ? "true" : "false");

 printf("dpeg.test_numeral1 ==> %s\n", dpeg__test_numeral1() ? "true" : "false");

 printf("dpeg.test_numeral2 ==> %s\n", dpeg__test_numeral2() ? "true" : "false");

 printf("dpeg.test_numeral3 ==> %s\n", dpeg__test_numeral3() ? "true" : "false");

 printf("dpeg.test_numeral4 ==> %s\n", dpeg__test_numeral4() ? "true" : "false");

 printf("dpeg.test_numeral5 ==> %s\n", dpeg__test_numeral5() ? "true" : "false");

 printf("dpeg.test_numeral6 ==> %s\n", dpeg__test_numeral6() ? "true" : "false");

 printf("dpeg.test_numeral7 ==> %s\n", dpeg__test_numeral7() ? "true" : "false");

 printf("dpeg.test_numeral8 ==> %s\n", dpeg__test_numeral8() ? "true" : "false");

 printf("dpeg.test_key1 ==> %s\n", dpeg__test_key1() ? "true" : "false");

 printf("dpeg.test_key2 ==> %s\n", dpeg__test_key2() ? "true" : "false");

 printf("dpeg.test_key3 ==> %s\n", dpeg__test_key3() ? "true" : "false");

 printf("dpeg.test_key4 ==> %s\n", dpeg__test_key4() ? "true" : "false");

 printf("dpeg.test_key5 ==> %s\n", dpeg__test_key5() ? "true" : "false");

 printf("dpeg.test_string1 ==> %s\n", dpeg__test_string1() ? "true" : "false");

 printf("dpeg.test_string1_1 ==> %s\n", dpeg__test_string1_1() ? "true" : "false");

 printf("dpeg.test_string2 ==> %s\n", dpeg__test_string2() ? "true" : "false");

 printf("dpeg.test_string3 ==> %s\n", dpeg__test_string3() ? "true" : "false");

 printf("dpeg.test_string3_1 ==> %s\n", dpeg__test_string3_1() ? "true" : "false");

 printf("dpeg.test_string4 ==> %s\n", dpeg__test_string4() ? "true" : "false");

 printf("dpeg.test_string4_1 ==> %s\n", dpeg__test_string4_1() ? "true" : "false");

 printf("dpeg.test_string5 ==> %s\n", dpeg__test_string5() ? "true" : "false");

 printf("dpeg.test_string5_1 ==> %s\n", dpeg__test_string5_1() ? "true" : "false");

 printf("dpeg.test_string6 ==> %s\n", dpeg__test_string6() ? "true" : "false");

 printf("dpeg.test_string6_1 ==> %s\n", dpeg__test_string6_1() ? "true" : "false");
}
