// test main ltedpegtest generated by make-c-tests-main

// Includes
#include "ltedpegtest_c.h"

int main () {

 printf("ltedpegtest.jsonpureparsefile_test1 ==> %s\n", ltedpegtest__jsonpureparsefile_test1() ? "true" : "false");

 printf("ltedpegtest.jsonpureparsefile_test2 ==> %s\n", ltedpegtest__jsonpureparsefile_test2() ? "true" : "false");

 printf("ltedpegtest.jsonpureparsefile_test3 ==> %s\n", ltedpegtest__jsonpureparsefile_test3() ? "true" : "false");

 printf("ltedpegtest.jsonpureparsefile_test_irModel ==> %s\n", ltedpegtest__jsonpureparsefile_test_irModel() ? "true" : "false");

 printf("ltedpegtest.jsonpureparsefile_test_prelude ==> %s\n", ltedpegtest__jsonpureparsefile_test_prelude() ? "true" : "false");
}
